Automatisera insättningar av `\begin{parasection}` och `\end{parasection}`
Dsek-LTH/dsekdocs pull request #30
Opened 2024-01-21 00:53 UTC by fnurkla

Raaah! Frihet från klumpig notation! 

Se diskussionen i slutet av #26 för fler detaljer.

2024-01-21 10:43 UTC, alfredgrip requested changes
Detta är nice quality of life ändring! Märkte däremot att om man skriver enligt
```
\section{Teknologia}

\paraitem{Råsa} En lämplig tolkning av råsa är \texttt{0xF280A1}. Detta kan
tolkas som Pantone 189 U eller 35,3\% svart.

\subsection{Hedersomnämnande}

\paraitem{Hedersmedlemmar}

```
, alltså slänger in en subsection istället för en section, så får både "Råsa" och "Hedersmedlemmar" paragrafnummer 1.1, men "Hedersmedlemmar" borde enligt mig då få nummer 1.1.1

2024-01-21 18:01 UTC, fnurkla commented
Detta ska vara fixat nu!

2024-01-21 19:42 UTC, fnurkla commented
På tal om ergonomi, skulle det vara rimligt att skugga `\paragraph{...}` med `\paraitem{...}`? Eftersom `\paragraph` är ett inbyggt kommando tror jag att de flesta redigeringsprogram kommer att fatta bättre om man gör det.

2024-01-22 09:03 UTC, alfredgrip approved these changes
Snyggt fixat! Ja det skadar nog inte att skugga `\paragraph`, kan va smidigt

2024-01-22 13:16 UTC, merged